#!/bin/sh /etc/rc.common
START=99

start() {
    echo "Starting All claim script"
    /root/airdrop/claimpy.sh &
}

stop() {
    echo "Stopping All claim script"
    #pgrep -f "/root/airdrop/" | xargs kill
}